# Generated by Django 4.2.9 on 2024-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_insensitive_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, db_collation='case_insensitive', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, db_collation='case_insensitive', max_length=150, verbose_name='last name'),
        ),
    ]
