# Generated by Django 4.2.9 on 2024-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_site'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "api_site" ALTER COLUMN "name" TYPE varchar(255) COLLATE "case_insensitive";
            ALTER TABLE "api_site" ADD UNIQUE(name);
            """,
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                model_name='Site',
                name='name',
                field= models.CharField(max_length=255, db_collation="case_insensitive", unique=True ),
                ),
            ],
        ),
    ]
