# Generated by Django 4.2.9 on 2024-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_collation_unique_to_name_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('open_hour', models.TimeField(blank=True, null=True)),
                ('close_hour', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
