# Generated by Django 4.2.9 on 2024-02-12 19:47

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_collation_unique_to_name_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Girl'), ('M', 'Boy'), ('MX', 'Mixed')], default='MX', max_length=20)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(models.ExpressionWrapper(django.db.models.functions.comparison.Coalesce('min_age', models.Value(-1)), output_field=models.IntegerField()), models.ExpressionWrapper(django.db.models.functions.comparison.Coalesce('max_age', models.Value(-1)), output_field=models.IntegerField()), models.F('gender'), name='unique_group'),
        ),
    ]
