# Generated by Django 4.2.9 on 2024-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_group_group_unique_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(choices=[('FR', 'Freestyle'), ('BR', 'Breaststroke'), ('BK', 'Backstroke'), ('FLY', 'Butterfly'), ('M', 'Medley')], max_length=20)),
                ('distance', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('RELAY', 'Relay')], default='INDIVIDUAL', max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.UniqueConstraint(fields=('stroke', 'distance', 'type'), name='unique_event_type'),
        ),
    ]
