# Generated by Django 4.2.9 on 2024-02-29 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_swimmeet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_collation='case_insensitive', max_length=150)),
                ('last_name', models.CharField(db_collation='case_insensitive', max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Girl'), ('M', 'Boy')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlethe_school_group', to='api.school')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlethe_session_group', to='api.session')),
            ],
        ),
    ]
