# Generated by Django 4.2.9 on 2024-02-29 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Time in minutes:seconds.milliseconds format', max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_record_athlete_group', to='api.athlete')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_record_event_type_group', to='api.eventtype')),
                ('swim_meet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_record_swim_meet_group', to='api.swimmeet')),
            ],
        ),
    ]
