# Generated by Django 4.2.9 on 2024-03-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_meetevent_meetevent_unique_num_event_swim_meet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DurationField(),
        ),
    ]
