# Generated by Django 4.2.9 on 2024-03-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_meetevent_meetevent_unique_num_event_swim_meet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_num', models.PositiveSmallIntegerField()),
                ('seed_time', models.CharField(help_text='Time in minutes:seconds.milliseconds format', max_length=15)),
                ('heat_time', models.CharField(help_text='Time in minutes:seconds.milliseconds format', max_length=15)),
                ('num_heat', models.PositiveSmallIntegerField()),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heat_athlete', to='api.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_event', to='api.meetevent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='heat',
            constraint=models.UniqueConstraint(fields=('event', 'lane_num', 'num_heat'), name='unique_event_lane_heat'),
        ),
    ]
