# Generated by Django 4.2.9 on 2024-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_heat_heat_unique_event_lane_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetevent',
            name='total_num_heats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
