# Generated by Django 4.2.9 on 2025-01-24 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_meetevent_total_num_heats'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmeet',
            name='num_lanes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
