# Generated by Django 4.2.9 on 2025-02-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_swimmeet_num_lanes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_swim_meets', to='api.athlete')),
                ('swim_meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_meet_athletes', to='api.swimmeet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('swim_meet', 'athlete'), name='unique_swim_meet_athlete'),
        ),
    ]
