# Generated by Django 4.2.9 on 2025-05-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(limit_choices_to={'event_type__type': 'RELAY'}, on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='api.meetevent')),
            ],
        ),
        migrations.CreateModel(
            name='RelayHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_num', models.PositiveSmallIntegerField()),
                ('seed_time', models.DurationField(blank=True, null=True)),
                ('heat_time', models.DurationField(blank=True, null=True)),
                ('num_heat', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(limit_choices_to={'event_type__type': 'RELAY'}, on_delete=django.db.models.deletion.CASCADE, related_name='relay_heats', to='api.meetevent')),
                ('relay', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_heat', to='api.relay')),
            ],
        ),
        migrations.CreateModel(
            name='RelayMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.relay')),
            ],
            options={
                'unique_together': {('relay', 'order')},
            },
        ),
        migrations.AddConstraint(
            model_name='relayheat',
            constraint=models.UniqueConstraint(fields=('event', 'lane_num', 'num_heat'), name='unique_relay_event_lane_heat'),
        ),
    ]
