# Generated by Django 4.2.9 on 2024-02-05 23:01

from django.db import migrations
from django.contrib.postgres.operations import CreateCollation


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
    ]
