version: "3"

services:
  db:
    image: postgres:14-alpine

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: 
      context: . #Sets the directory for docker-compose to build.

    # Handles the command used to run the project in the Docker container.
    command: python manage.py runserver 0.0.0.0:8000

    # Copy changes made to the project to your image in real-time.
    volumes: 
      - .:/code

    # Maps port on the local machine to port on Docker image
    ports: 
      - "8000:8000"

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    depends_on:
      - db